### ISSUE TITLE
Make the site conform to alpha.austin.gov branding where feasible

### ISSUE THREAD

**Issue by easherma** [cityofaustin/affordable-housing-search-clientside#5]
# As a potential applicant, I want to trust that the site I am using is safe to use and is an accurate, reputable source of information. 

**Is your feature request related to a problem? Please describe.**
The site is designed to stand alone, which means users will be finding it through searches or being linked straight to it. This means that we need to do a good job visually indicating the source of the application and its content, so users know they can trust it and that it will be a valuable source of info. 

We've begun to address these issues and work towards what we hope will eventually be a unified branding experience for projects in our portfolio. This is a driving force behind many of the decisions behind the design of https://alpha.austin.gov/ , and is very heavily inspired & informed by [similar work at the federal level](https://designsystem.digital.gov/). 

**Describe the solution you'd like**
Ideally we'd have a full-featured design system that is code-based and ready to be imported into projects. However, we're not there yet. But the process of helping make this project match our brand and styles can help get us there.

What we can do is use the visual styling as a guide for tweaking the current codebase for this project, and potentially clean up some of the existing styling in the process. 

**Additional context**
Kristin made some inital mocks here:
https://kristintaylor518545.invisionapp.com/overview/Affordable-Housing-Search-Form-Mobile-ck7ly8l3d03q20150fxgym8w2/screens?v=6uRkXfdl56G0CNv6l730tA%3D%3D&linkshare=urlcopied

These are based off our designs for alpha.austin.gov (checking if we have a publicly available version of these mocks)

In some ways, this is kind of a big issue. It might make sense to split this up into smaller issues. For now this checklist will suffice:

- [ ] colors
- [ ] typography
- [ ] 'offical website' banner
- [ ] spacing, corner radius, etc

**Comment by fshotlow** [comment]
issue is 4 years old. closing
